### ISSUE TITLE
Project Gradle Address?

### ISSUE THREAD

**Issue by shiyu0599** [multidots/android-app-common-tasks#4]
Hi,i want to import this utils to my android project,but what is the gradle address of this code?Thanks!

**Comment by lionel8486** [comment]
Hi there, not sure what you mean by "gradle address of this code"

**Comment by spyhunter99** [comment]
probably referring to the maven artifact id, group id, version and qualifier

**Comment by ninjanero** [comment]
i get an error in gradle.. Failed to resolve: com.github.CommonUtils:android:4acba4e

**Comment by mayankmultidots** [comment]
Hi,

We are not contribute our lib on Gradle or Maven.
You can check our "CommonUtils" for access all the common methods.


Thanks
Mayank

Mayank Dudhatra
*Team Leader Android*

*MultiDots Solution Pvt.Ltd.*

**Comment by gautamlakum** [comment]
Hi All,
We're looking forward to uploading this library to the Gradle. We will update the details soon.
Thank you

**Comment by kevalpatel2106** [comment]
Hi,

Here is the Gradle dependency to the library. Add following lines to the build.gradle file.
```
repositories {
    maven {
        url  "http://dl.bintray.com/multidots/md-maven" 
    }
}
dependency {
    compile 'com.multidots:common-task:1.0'
}
```
